import { Download, Email } from '@mui/icons-material';
import { Box, Button, Chip, Snackbar, Table, TableBody, TableCell, TableHead, TableRow, Typography } from '@mui/material';
import { useEffect, useState } from 'react';
import { useSelector } from 'react-redux';
import { TableState } from '../components/DataStates.jsx';
import { ROLES } from '../config/access.js';
import PageHeader from '../components/PageHeader.jsx';
import { api, downloadFile } from '../services/api.js';
import { formatCurrency } from '../utils/formatters.js';

export default function DocumentsPage() {
  const role = useSelector((state) => state.auth.user?.role);
  const canManageInvoices = role === ROLES.ADMIN || role === ROLES.PROCUREMENT_OFFICER;
  const [purchaseOrders, setPurchaseOrders] = useState([]);
  const [invoices, setInvoices] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [message, setMessage] = useState('');

  const load = async () => {
    try {
      setLoading(true);
      setError('');
      const [poResponse, invoiceResponse] = await Promise.all([
        api.get('/procurement/invoice/purchase-orders'),
        api.get('/procurement/invoice')
      ]);
      setPurchaseOrders(poResponse.data);
      setInvoices(invoiceResponse.data);
    } catch {
      setError('Purchase order and invoice data could not be loaded.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { load(); }, []);

  const emailInvoice = async (id) => {
    try {
      await api.post(`/procurement/invoice/${id}/send-email`);
      setMessage('Invoice email sent.');
    } catch {
      setMessage('Invoice email could not be sent.');
    }
  };

  return (
    <>
      <PageHeader
        title="Purchase Orders & Invoices"
        subtitle="Purchase orders and invoices are generated automatically after manager approval."
      />
      <Box className="data-card" sx={{ mb: 2 }}>
        <Box className="table-toolbar">
          <Box>
            <Typography className="table-toolbar-title">Purchase orders</Typography>
            <Typography className="table-toolbar-description">Orders generated by approved quotations.</Typography>
          </Box>
          <Chip label={`${purchaseOrders.length} orders`} />
        </Box>
        <Table>
          <TableHead>
            <TableRow>
              <TableCell>PO Number</TableCell>
                <TableCell>RFQ</TableCell>
              <TableCell>Total</TableCell>
              <TableCell>Status</TableCell>
              <TableCell align="right">Actions</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            <TableState loading={loading} error={error} empty={!purchaseOrders.length} colSpan={5} emptyTitle="No purchase orders generated" onRetry={load} />
            {purchaseOrders.map((po) => (
              <TableRow key={po.id}>
                <TableCell>{po.poNumber}</TableCell>
                <TableCell>{po.rfq?.title || `RFQ #${po.rfq?.id}`}</TableCell>
                <TableCell><strong>{formatCurrency(po.totalAmount)}</strong></TableCell>
                <TableCell><Chip size="small" label={po.status} /></TableCell>
                <TableCell align="right">
                  <Typography color="text.secondary" sx={{ fontSize: '.72rem' }}>Generated with approval</Typography>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </Box>
      <Box className="data-card">
        <Box className="table-toolbar">
          <Box>
            <Typography className="table-toolbar-title">Invoices</Typography>
            <Typography className="table-toolbar-description">Review totals, download PDFs, and send documents to vendors.</Typography>
          </Box>
          <Chip label={`${invoices.length} invoices`} />
        </Box>
        <Table>
          <TableHead>
            <TableRow>
              <TableCell>Invoice</TableCell>
                <TableCell>Tax</TableCell>
                <TableCell>Total</TableCell>
                <TableCell>Status</TableCell>
              <TableCell align="right">Actions</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            <TableState loading={loading} error={error} empty={!invoices.length} colSpan={5} emptyTitle="No invoices generated" onRetry={load} />
            {invoices.map((invoice) => (
              <TableRow key={invoice.id}>
                <TableCell>{invoice.invoiceNumber}</TableCell>
                <TableCell>{formatCurrency(invoice.taxAmount)}</TableCell>
                <TableCell><strong>{formatCurrency(invoice.totalAmount)}</strong></TableCell>
                <TableCell><Chip size="small" label={invoice.status} /></TableCell>
                <TableCell align="right">
                  {canManageInvoices ? (
                    <>
                      <Button startIcon={<Download />} onClick={() => downloadFile(`/procurement/invoice/${invoice.id}/download`, `${invoice.invoiceNumber}.pdf`)}>PDF</Button>
                      <Button startIcon={<Email />} onClick={() => emailInvoice(invoice.id)}>Email</Button>
                    </>
                  ) : (
                    <Typography color="text.secondary" sx={{ fontSize: '.72rem' }}>Read only</Typography>
                  )}
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </Box>
      <Snackbar open={Boolean(message)} autoHideDuration={3500} onClose={() => setMessage('')} message={message} />
    </>
  );
}
