import { Box, Chip, List, ListItem, ListItemText, Typography } from '@mui/material';
import { useEffect, useState } from 'react';
import { StateContent } from '../components/DataStates.jsx';
import PageHeader from '../components/PageHeader.jsx';
import { api } from '../services/api.js';

export default function NotificationsPage() {
  const [notifications, setNotifications] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const load = async () => {
    try {
      setLoading(true);
      setError('');
      const { data } = await api.get('/activities');
      setNotifications(data);
    } catch {
      setError('Activity history could not be loaded.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { load(); }, []);

  return (
    <>
      <PageHeader title="Activity & Logs" subtitle="A chronological record of RFQ, quotation, approval, PO, and invoice events." />
      <div className="data-card">
        <Box className="table-toolbar">
          <Box>
            <Typography className="table-toolbar-title">Procurement activity</Typography>
            <Typography className="table-toolbar-description">Immutable workflow events generated by the backend state machine.</Typography>
          </Box>
          <Chip label={`${notifications.length} recent events`} />
        </Box>
        {loading || error || !notifications.length ? (
          <StateContent
            loading={loading}
            error={error}
            onRetry={load}
            title="No activity recorded yet"
            description="RFQ, approval, PO, and invoice events will appear here."
          />
        ) : <List>
          {notifications.map((item, index) => (
            <ListItem
              key={item.id}
              className="activity-item"
              divider={index < notifications.length - 1}
              sx={{ py: 1.8, px: 2 }}
            >
              <Box sx={{ width: 10, height: 10, mr: 2, borderRadius: '50%', flexShrink: 0, bgcolor: 'primary.main', boxShadow: '0 0 0 4px #e2f3e9' }} />
              <ListItemText
                primary={`${item.eventType?.replaceAll('_', ' ')} · ${item.entityType} #${item.entityId}`}
                secondary={`${item.remarks || 'State changed'} · ${item.actorName} · ${new Date(item.timestamp).toLocaleString()}`}
                primaryTypographyProps={{ fontWeight: 700, fontSize: '.84rem' }}
                secondaryTypographyProps={{ fontSize: '.74rem', mt: 0.4 }}
              />
            </ListItem>
          ))}
        </List>}
      </div>
    </>
  );
}
