spring:
  application:
    name: VendorBridge Backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/vendorbridge}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: ${SERVER_PORT:8088}

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970 # 256-bit Hex Key for HMAC-SHA256
      expiration: 86400000 # a day
